# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7861d8f47d1515cfaba0db96da2513fd5cb6219178061b31e40ba1322f97ede0e23f75c7949569ba1b69f9d6ba3bc79748535028086711eff978c5324c84b897

test:
  secret_key_base: d153197fa8e2115543f52ba912f05883850df331f21eed3742f007a8a146b39e8c32eb0cdda62d46f974468321130ffb65d29c15f6a5bb475584cc6aece52e3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
